package Server;

public enum MessageType {
    USER_CONNECTED,
    USER_DISCONNECTED,
    USER_NAME,
    TEXT,
    NAME_REQUEST,
    PUBLIC_KEY_USER,
    PUBLIC_KEY_SERVER,
    NAME_NOT_ACCEPTED,
    USERS_LIST
}
